// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/users/service.proto

/*
Package users is a generated protocol buffer package.

It is generated from these files:
	proto/users/service.proto

It has these top-level messages:
	CreateUserRequest
	CreateUserResponse
	GetAllUsersRequest
	GetAllUsersResponse
	User
*/
package users

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUserRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateUserResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Code    uint64 `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateUserResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAllUsersRequest struct {
}

func (m *GetAllUsersRequest) Reset()                    { *m = GetAllUsersRequest{} }
func (m *GetAllUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllUsersRequest) ProtoMessage()               {}
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetAllUsersResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
	Code  uint64  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
}

func (m *GetAllUsersResponse) Reset()                    { *m = GetAllUsersResponse{} }
func (m *GetAllUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllUsersResponse) ProtoMessage()               {}
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetAllUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *GetAllUsersResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type User struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "users.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "users.CreateUserResponse")
	proto.RegisterType((*GetAllUsersRequest)(nil), "users.GetAllUsersRequest")
	proto.RegisterType((*GetAllUsersResponse)(nil), "users.GetAllUsersResponse")
	proto.RegisterType((*User)(nil), "users.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Users service

type UsersClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*GetAllUsersResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := grpc.Invoke(ctx, "/users.Users/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*GetAllUsersResponse, error) {
	out := new(GetAllUsersResponse)
	err := grpc.Invoke(ctx, "/users.Users/GetAllUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetAllUsers(context.Context, *GetAllUsersRequest) (*GetAllUsersResponse, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.Users/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.Users/GetAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetAllUsers(ctx, req.(*GetAllUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Users_CreateUser_Handler,
		},
		{
			MethodName: "GetAllUsers",
			Handler:    _Users_GetAllUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/users/service.proto",
}

func init() { proto.RegisterFile("proto/users/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x76, 0xf3, 0xa3, 0x38, 0x01, 0xc1, 0xb1, 0x87, 0x6d, 0x4e, 0x75, 0x4f, 0x3d, 0xa5, 0x50,
	0xcf, 0x82, 0x52, 0xd0, 0x8b, 0xa7, 0x80, 0x0f, 0x10, 0x9b, 0x41, 0x02, 0x49, 0x53, 0x77, 0x52,
	0x9f, 0xc4, 0x07, 0x96, 0x4c, 0xb2, 0x9a, 0x92, 0xbd, 0xcd, 0x7c, 0x33, 0xfb, 0xfd, 0xcc, 0xc2,
	0xf2, 0x68, 0xdb, 0xae, 0xdd, 0x9c, 0x98, 0x2c, 0x6f, 0x98, 0xec, 0x77, 0xb5, 0xa7, 0x4c, 0x30,
	0x8c, 0x05, 0x34, 0x8f, 0x70, 0xbb, 0xb3, 0x54, 0x74, 0xf4, 0xce, 0x64, 0x73, 0xfa, 0x3a, 0x11,
	0x77, 0x88, 0x10, 0x1d, 0x8a, 0x86, 0xb4, 0x5a, 0xa9, 0xf5, 0x75, 0x2e, 0x35, 0x2e, 0x20, 0xa6,
	0xa6, 0xa8, 0x6a, 0x1d, 0x08, 0x38, 0x34, 0x26, 0x07, 0x9c, 0x3e, 0xe7, 0x63, 0x7b, 0x60, 0x42,
	0x0d, 0x57, 0x0d, 0x31, 0x17, 0x9f, 0x8e, 0xc2, 0xb5, 0x3d, 0xf3, 0xbe, 0x2d, 0x49, 0x48, 0xa2,
	0x5c, 0x6a, 0xbc, 0x81, 0xa0, 0x2a, 0x75, 0x28, 0x8b, 0x41, 0x55, 0x9a, 0x05, 0xe0, 0x2b, 0x75,
	0xcf, 0x75, 0xdd, 0x73, 0xf2, 0xe8, 0xc9, 0xbc, 0xc1, 0xdd, 0x19, 0x3a, 0x4a, 0xdd, 0xc3, 0x10,
	0x44, 0xab, 0x55, 0xb8, 0x4e, 0xb6, 0x49, 0x26, 0x5d, 0x26, 0x76, 0x86, 0x89, 0x4f, 0xd3, 0x3c,
	0x41, 0xd4, 0xaf, 0x8c, 0xda, 0xca, 0x69, 0xff, 0x25, 0x0f, 0x7c, 0xc9, 0xc3, 0x49, 0xf2, 0xed,
	0x8f, 0x82, 0x58, 0xac, 0xe0, 0x0e, 0xe0, 0xff, 0x06, 0xa8, 0x47, 0x07, 0xb3, 0xab, 0xa6, 0x4b,
	0xcf, 0x64, 0x48, 0x61, 0x2e, 0xf0, 0x05, 0x92, 0x49, 0x3c, 0x74, 0xbb, 0xf3, 0x43, 0xa4, 0xa9,
	0x6f, 0xe4, 0x78, 0x3e, 0x2e, 0xe5, 0x77, 0x1f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x58, 0xa2,
	0x43, 0xe2, 0xfa, 0x01, 0x00, 0x00,
}
