// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/list/service.proto

/*
Package list is a generated protocol buffer package.

It is generated from these files:
	proto/list/service.proto

It has these top-level messages:
	CreateItemRequest
	CreateItemResponse
	GetUserItemsRequest
	GetUserItemsResponse
	Item
	DeleteItemRequest
	DeleteItemResponse
*/
package list

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateItemRequest struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
}

func (m *CreateItemRequest) Reset()                    { *m = CreateItemRequest{} }
func (m *CreateItemRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateItemRequest) ProtoMessage()               {}
func (*CreateItemRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateItemRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateItemRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CreateItemResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Code    uint64 `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
}

func (m *CreateItemResponse) Reset()                    { *m = CreateItemResponse{} }
func (m *CreateItemResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateItemResponse) ProtoMessage()               {}
func (*CreateItemResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateItemResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateItemResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type GetUserItemsRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
}

func (m *GetUserItemsRequest) Reset()                    { *m = GetUserItemsRequest{} }
func (m *GetUserItemsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserItemsRequest) ProtoMessage()               {}
func (*GetUserItemsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserItemsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserItemsResponse struct {
	Items []*Item `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Code  uint64  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
}

func (m *GetUserItemsResponse) Reset()                    { *m = GetUserItemsResponse{} }
func (m *GetUserItemsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserItemsResponse) ProtoMessage()               {}
func (*GetUserItemsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserItemsResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *GetUserItemsResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type Item struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	UserId  string `protobuf:"bytes,3,opt,name=userId" json:"userId,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Item) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteItemRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteItemRequest) Reset()                    { *m = DeleteItemRequest{} }
func (m *DeleteItemRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteItemRequest) ProtoMessage()               {}
func (*DeleteItemRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteItemResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Code    uint64 `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
}

func (m *DeleteItemResponse) Reset()                    { *m = DeleteItemResponse{} }
func (m *DeleteItemResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteItemResponse) ProtoMessage()               {}
func (*DeleteItemResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteItemResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeleteItemResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateItemRequest)(nil), "list.CreateItemRequest")
	proto.RegisterType((*CreateItemResponse)(nil), "list.CreateItemResponse")
	proto.RegisterType((*GetUserItemsRequest)(nil), "list.GetUserItemsRequest")
	proto.RegisterType((*GetUserItemsResponse)(nil), "list.GetUserItemsResponse")
	proto.RegisterType((*Item)(nil), "list.Item")
	proto.RegisterType((*DeleteItemRequest)(nil), "list.DeleteItemRequest")
	proto.RegisterType((*DeleteItemResponse)(nil), "list.DeleteItemResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for List service

type ListClient interface {
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error)
	GetUserItems(ctx context.Context, in *GetUserItemsRequest, opts ...grpc.CallOption) (*GetUserItemsResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error)
}

type listClient struct {
	cc *grpc.ClientConn
}

func NewListClient(cc *grpc.ClientConn) ListClient {
	return &listClient{cc}
}

func (c *listClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error) {
	out := new(CreateItemResponse)
	err := grpc.Invoke(ctx, "/list.List/CreateItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listClient) GetUserItems(ctx context.Context, in *GetUserItemsRequest, opts ...grpc.CallOption) (*GetUserItemsResponse, error) {
	out := new(GetUserItemsResponse)
	err := grpc.Invoke(ctx, "/list.List/GetUserItems", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error) {
	out := new(DeleteItemResponse)
	err := grpc.Invoke(ctx, "/list.List/DeleteItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for List service

type ListServer interface {
	CreateItem(context.Context, *CreateItemRequest) (*CreateItemResponse, error)
	GetUserItems(context.Context, *GetUserItemsRequest) (*GetUserItemsResponse, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error)
}

func RegisterListServer(s *grpc.Server, srv ListServer) {
	s.RegisterService(&_List_serviceDesc, srv)
}

func _List_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.List/CreateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _List_GetUserItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).GetUserItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.List/GetUserItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).GetUserItems(ctx, req.(*GetUserItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _List_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.List/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _List_serviceDesc = grpc.ServiceDesc{
	ServiceName: "list.List",
	HandlerType: (*ListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItem",
			Handler:    _List_CreateItem_Handler,
		},
		{
			MethodName: "GetUserItems",
			Handler:    _List_GetUserItems_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _List_DeleteItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/list/service.proto",
}

func init() { proto.RegisterFile("proto/list/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x9b, 0x74, 0xad, 0x38, 0x8a, 0xd0, 0x51, 0x74, 0xed, 0x29, 0xac, 0x97, 0x5e, 0x4c,
	0xa1, 0x3e, 0x41, 0xfd, 0x43, 0x2d, 0xf4, 0x14, 0xf0, 0x01, 0x6a, 0x33, 0xc8, 0x42, 0x63, 0x6a,
	0x66, 0xeb, 0x9b, 0xfa, 0x3e, 0xb2, 0x9b, 0xae, 0x49, 0x4c, 0xf4, 0xe0, 0x2d, 0x3b, 0x33, 0x7c,
	0xdf, 0x37, 0xbf, 0x09, 0xc8, 0x6d, 0x91, 0x9b, 0x7c, 0xb2, 0xd1, 0x6c, 0x26, 0x4c, 0xc5, 0x87,
	0x5e, 0x53, 0xec, 0x4a, 0x28, 0x6c, 0x4d, 0x3d, 0xc2, 0xf0, 0xbe, 0xa0, 0x95, 0xa1, 0x85, 0xa1,
	0x2c, 0xa1, 0xf7, 0x1d, 0xb1, 0x41, 0x09, 0x87, 0x19, 0x31, 0xaf, 0x5e, 0x49, 0x06, 0x51, 0x30,
	0x3e, 0x4a, 0xfc, 0x13, 0x2f, 0x60, 0xb0, 0x63, 0x2a, 0x16, 0xa9, 0x0c, 0x5d, 0x63, 0xff, 0x52,
	0x77, 0x80, 0x75, 0x19, 0xde, 0xe6, 0x6f, 0x4c, 0x7f, 0xe8, 0x20, 0x88, 0x75, 0x9e, 0x92, 0x53,
	0x11, 0x89, 0xfb, 0x56, 0x37, 0x70, 0x36, 0x27, 0xf3, 0x6c, 0x05, 0x0d, 0x65, 0xec, 0xc3, 0x54,
	0x96, 0x41, 0xc3, 0x72, 0x09, 0xe7, 0xcd, 0xf1, 0xbd, 0x69, 0x04, 0x07, 0xda, 0x16, 0x64, 0x10,
	0xf5, 0xc7, 0xc7, 0x53, 0x88, 0xed, 0x9e, 0xb1, 0xcb, 0x55, 0x36, 0x3a, 0xcd, 0x9f, 0x40, 0xd8,
	0x11, 0x3c, 0x85, 0x50, 0x7b, 0xa7, 0x50, 0xa7, 0xf5, 0x15, 0xc2, 0xdf, 0x50, 0xf4, 0x1b, 0xb9,
	0xae, 0x61, 0xf8, 0x40, 0x1b, 0x6a, 0x12, 0xfd, 0x21, 0x6b, 0x79, 0xd5, 0x87, 0xfe, 0xc3, 0x6b,
	0xfa, 0x19, 0x80, 0x58, 0x6a, 0x36, 0x38, 0x03, 0xa8, 0xe0, 0xe3, 0x65, 0xb9, 0x70, 0xeb, 0xaa,
	0x23, 0xd9, 0x6e, 0x94, 0xbe, 0xaa, 0x87, 0x73, 0x38, 0xa9, 0xc3, 0xc4, 0xab, 0x72, 0xb6, 0xe3,
	0x1e, 0xa3, 0x51, 0x57, 0xeb, 0x5b, 0x68, 0x06, 0x50, 0x2d, 0xe6, 0xb3, 0xb4, 0x78, 0xf8, 0x2c,
	0x6d, 0x06, 0xaa, 0xf7, 0x32, 0x70, 0xff, 0xe7, 0xed, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24,
	0xaa, 0xf5, 0xaf, 0xbb, 0x02, 0x00, 0x00,
}
